Update bitrise.yml

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -193,6 +193,16 @@ workflows:
     - _run
 
   test_test_plan_enabled_project:
+    steps:
+    - script:
+        run_if: "{{enveq \"BITRISEIO_STACK_ID\" \"osx-xcode-14.3.x-edge\"}}"
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -x # Do not set -e as bitrise command is expected to fail
+            bitrise run --config=./e2e/bitrise.yml utility_test_test_plan_enabled_project
+
+  utility_test_test_plan_enabled_project:
     envs:
     - SAMPLE_APP_URL: https://github.com/bitrise-io/sample-swift-project-with-parallel-ui-test.git
     - SAMPLE_APP_BRANCH: master
@@ -203,14 +213,20 @@ workflows:
     - CODE_SIGNING_METHOD: "off"
     before_run:
     - _run
-    steps:
-    - script:
-        inputs:
-        - content: env
     after_run:
     - _run_test_without_building
 
   test_test_plan_enabled_project_test_plan_specified:
+    steps:
+    - script:
+        run_if: "{{enveq \"BITRISEIO_STACK_ID\" \"osx-xcode-14.3.x-edge\"}}"
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -x # Do not set -e as bitrise command is expected to fail
+            bitrise run --config=./e2e/bitrise.yml utility_test_test_plan_enabled_project_test_plan_specified
+
+  utility_test_test_plan_enabled_project_test_plan_specified:
     envs:
     - SAMPLE_APP_URL: https://github.com/bitrise-io/sample-swift-project-with-parallel-ui-test.git
     - SAMPLE_APP_BRANCH: master
